import * as fs from 'node:fs';
import * as path from 'node:path';

import { Construct, Node } from 'constructs';
import * as yaml from 'js-yaml';

import type { CompositeAction } from '#src/composite-action.ts';
import { resolveTokens } from '#src/expressions.ts';
import { Workflow } from '#src/workflow.ts';

/**
 * Represents a cdkaction stack.
 */
export class Stack extends Construct {
  /**
   * The unique identifier for the stack.
   */
  private readonly id: string;

  private readonly compositeActions = new Map<string, CompositeAction>();

  /**
   * Walks up the construct tree to find the enclosing Stack.
   */
  public static of(construct: Construct): Stack {
    let current: Construct | undefined = construct;
    while (current) {
      if (current instanceof Stack) {
        return current;
      }
      current = Node.of(current).scope as Construct | undefined;
    }
    throw new Error(`No Stack found in the construct tree above '${Node.of(construct).path}'`);
  }

  /**
   * Defines a cdkaction stack.
   * @param scope cdkaction app.
   * @param id a unique identifier for the stack.
   */
  public constructor(scope: Construct, id: string) {
    super(scope, id);
    this.id = id;
  }

  /**
   * Registers a composite action for synthesis. Idempotent — calling
   * multiple times with the same action is a no-op.
   */
  public registerCompositeAction(action: CompositeAction): void {
    this.compositeActions.set(action.actionDirectory, action);
  }

  /**
   * Synthesizes the stack's workflows to the output directory.
   * @param outdir The output directory to write manifests to.
   */
  public synthesize(outdir: string): void {
    const header = `# Generated by cdkactions. Do not modify\n# Generated as part of the '${this.id}' stack.\n`;
    for (const child of Node.of(this).children) {
      if (child instanceof Workflow) {
        const workflowOutput = path.join(outdir, child.outputFile);
        const resolved = resolveTokens(child.toGHAction()) as Record<string, unknown>;
        const rawYaml = dumpWorkflow(resolved);

        fs.writeFileSync(workflowOutput, header + rawYaml);
      }
    }

    for (const action of this.compositeActions.values()) {
      const actionsDir = path.resolve(outdir, '..', 'actions', action.actionDirectory);
      fs.mkdirSync(actionsDir, { recursive: true });

      const actionOutput = path.join(actionsDir, 'action.yml');
      const rawYaml = yaml.dump(resolveTokens(action.toGHAction()), YAML_OPTIONS);

      fs.writeFileSync(actionOutput, header + rawYaml);
    }
  }
}

const YAML_OPTIONS = {
  lineWidth: -1,
  noCompatMode: true,
  quotingType: '"',
  sortKeys: true,
} as const;

function dumpWorkflow(obj: Record<string, unknown>): string {
  const { jobs, ...rest } = obj;
  const topYaml = yaml.dump(rest, YAML_OPTIONS);
  const jobsYaml = yaml.dump({ jobs }, YAML_OPTIONS);
  return topYaml + jobsYaml;
}
