import * as fs from 'node:fs';
import * as path from 'node:path';

import { Construct, Node } from 'constructs';
import * as yaml from 'js-yaml';

import { Workflow } from './workflow.js';

/**
 * Represents a cdkaction stack.
 */
export class Stack extends Construct {
  private readonly id: string;

  public constructor(scope: Construct, id: string) {
    super(scope, id);
    this.id = id;
  }

  public synthesize(outdir: string): void {
    for (const child of Node.of(this).children) {
      if (child instanceof Workflow) {
        const workflowOutput = path.join(outdir, child.outputFile);
        const rawYaml = yaml.dump(child.toGHAction(), { lineWidth: -1, noCompatMode: true, quotingType: '"' });
        fs.writeFileSync(
          workflowOutput,
          `# Generated by cdkactions. Do not modify\n# Generated as part of the '${this.id}' stack.\n`,
        );
        fs.writeFileSync(workflowOutput, rawYaml, { flag: 'a' });
      }
    }
  }
}
